; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:pro_mini]
platform = atmelavr
board = pro16MHzatmega328
framework = arduino
build_flags =
	-DUGV_BOARD_PRO_MINI

[env:esp32d]
platform = espressif32
board = esp32dev
framework = arduino
build_type = release
build_flags =
	-DUGV_BOARD_ESP32D
	-DDEBUG_MODE=0
lib_deps =
    https://github.com/cotestatnt/async-esp-fs-webserver.git
    https://github.com/ESP32Async/ESPAsyncWebServer.git
    https://github.com/ESP32Async/AsyncTCP.git

[env:esp32d_debug]
platform = espressif32
board = esp32dev
framework = arduino
build_type = debug
build_flags =
	-DUGV_BOARD_ESP32D
    -DDEBUG_MODE=1
lib_deps =
    https://github.com/cotestatnt/async-esp-fs-webserver.git
    https://github.com/ESP32Async/ESPAsyncWebServer.git
    https://github.com/ESP32Async/AsyncTCP.git


[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
build_flags =
	-DUGV_BOARD_ESP32S3
lib_deps =
    https://github.com/cotestatnt/async-esp-fs-webserver.git
    https://github.com/ESP32Async/ESPAsyncWebServer.git
    https://github.com/ESP32Async/AsyncTCP.git
